### ISSUE TITLE
背景图片问题

### ISSUE THREAD

**Issue by z605666069** [xlfsummer/mp-painter#15]
设置海报需要设置背景图片，普通使用图片的时候位置会被占用， 如果设置背景图片position: 'absolute' 时候，海报上的所有图片、文字都需要绝对定位导致text align center 等无法生效，希望设置一个z-index 之类的可以设置层级的东西，使背景图和普通的分开

**Comment by xlfsummer** [comment]
可以只将背景绝对定位，其它不设置绝对定位

如下：
- container
  - image   <- 背景图，绝对定位
  - text       <- 文字，静态定位
  - image   <- 其它图片，静态定位

**Comment by z605666069** [comment]
ok 谢谢
