### ISSUE TITLE
ios 模拟器 [ERROR] : preloadImage error

### ISSUE THREAD

**Issue by z605666069** [xlfsummer/mp-painter#16]
log:
12:08:41.520 [LOG] : 调用小程序drawImage，使用:, _doc/uniapp_temp_1591589319571/download/ at node_modules/mp-painter/dist/lib/painter.js:1 
12:08:41.541 [LOG] : 绘制图片: 下载图片文件:, _doc/uniapp_temp_1591589319571/canvas/1591589320552.jpg at node_modules/mp-painter/dist/lib/painter.js:1 
12:08:41.562 [LOG] : 调用小程序drawImage，使用:, _doc/uniapp_temp_1591589319571/download/ at node_modules/mp-painter/dist/lib/painter.js:1 
12:08:41.587 [ERROR] : preloadImage error

**Comment by xlfsummer** [comment]
应该是没有下载到图片，可以把 draw 里面的内容发出来看看吗，主要看图片的路径。
当然，如果能搭建一个复现问题的简洁的 demo 就最好了。

**Comment by z605666069** [comment]
原因找到了， 因为我是使用
import bg from '@/static/bg.png'

content里面使用的是 
	```
                                                           {
								type: "image", top: 0, left: 0, width: 750, height: 1624,
								position: 'absolute',
								src:bg,
							},
```

这样使用的话  H5是没问题的  在模拟器上会报错  [ERROR] : preloadImage error

正确的使用方法：

	```
                                                           {
								type: "image", top: 0, left: 0, width: 750, height: 1624,
								position: 'absolute',
								src:‘../static/bg.png’,
							},
```

请问如何才能使用绝对路径这种引入方式

**Comment by xlfsummer** [comment]
经测试，微信小程序预览中支持绝对路径格式

**Comment by xlfsummer** [comment]
尽量不要使用本地图片地址，如果一定要使用，建议使用 / 开头的绝对路径，而不是使用 `import` 来导入
参见示例 https://mp-painter.xlf-summer.cn/#/pages/image/image
