### ISSUE TITLE
qrcode  ios模拟器上无法使用，H5可以使用

### ISSUE THREAD

**Issue by z605666069** [xlfsummer/mp-painter#17]
ios 模拟器 [ERROR] : preloadImage error
同样的问题，qrcode 生成本地临时地址，一旦遇到了本地临时地址，就会报这个错

**Comment by xlfsummer** [comment]
可以把临时地址发出来看看吗

**Comment by xlfsummer** [comment]
应该是被转成了 base64, 小程序预览时 canvas 不支持 base64 图片的绘制。
可参考 [示例](https://mp-painter.xlf-summer.cn/#/pages/image/image) 以及对应的 [源码说明](https://github.com/xlfsummer/mp-painter/blob/72557e4d287fe39b1e47ebc597bc38a1b8ea63dc/example/src/pages/image/image.vue#L18)
