### ISSUE TITLE
demo 中增加导出图片的示例

### ISSUE THREAD

**Issue by xlfsummer** [xlfsummer/mp-painter#18]
https://ask.dcloud.net.cn/question/99598?notification_id-754666__rf-false__source-MTM1NTMy

**Comment by buhtib** [comment]
uni希望可以增加一个 导出图片临时链接的方法，，目前只能看到不能获取到

**Comment by xlfsummer** [comment]
> uni希望可以增加一个 导出图片临时链接的方法，，目前只能看到不能获取到

导出图片请直接使各平台提供的 [API](https://github.com/xlfsummer/mp-painter/wiki/%E5%B0%86%E7%BB%98%E5%88%B6%E7%BB%93%E6%9E%9C%E5%AF%BC%E5%87%BA%E4%B8%BA%E5%9B%BE%E7%89%87)
