### ISSUE TITLE
绘制图片支持 object-position 属性

### ISSUE THREAD

**Issue by xlfsummer** [xlfsummer/mp-painter#21]
在绘制图片时支持 [object-position](https://developer.mozilla.org/zh-CN/docs/Web/CSS/object-position) 属性，用于控制图片显示的位置

**Comment by qianjue520** [comment]
![微信截图_20200623175831](https://user-images.githubusercontent.com/50491060/85390503-7c587c00-b57b-11ea-8818-5797afa02cd4.png)作者你好，我要画的海报是这个样子的，除了上方图片，其他的都可以了，这个上方图片的宽高是固定的，但是图片本身有长有短，我想取图片上方的部分，不变形就好，刚才我试了一下你说的 object-position属性，但是我没成功，我看源码中，也并未见这个属性值哎
![微信截图_20200623182407](https://user-images.githubusercontent.com/50491060/85392933-cbec7700-b57e-11ea-9a69-0b233948d2c9.png)

**Comment by xlfsummer** [comment]
是的，目前还不支持，用这个名字是因为对应的 CSS 属性叫作这个名字。到时候新加的属性也会叫这个名字。

**Comment by xlfsummer** [comment]
计划增加 `objectPosition` 属性
- 类型为 `["top" | "center" | "bottom", "left" | "center" | "right"]`
- 默认值为 `["center", "center"]`
- 不支持百分数及数字值

**Comment by qianjue520** [comment]
嗯，这个可以的，用这个就可以取图片上的某个部分，，这个插件制作的非常简单清晰，再复杂的海报，都能画出来，非常棒，加油，插件市场大赛开始了，祝作者取得一个好成绩

**Comment by z605666069** [comment]
支持 我也很需求这个东西，目前裁剪到中间部分没办法换位置 ，如果能换位置就完美了

**Comment by qianjue520** [comment]
作者，我在组件中使用此插件无效，这是个什么问题

**Comment by xlfsummer** [comment]
> 作者，我在组件中使用此插件无效，这是个什么问题

不相关的问题请创建一个新的 issue

**Comment by xlfsummer** [comment]
已发布 [v0.2.6](../releases/tag/v0.2.6)
