### ISSUE TITLE
图像使用height: "auto"会报错

### ISSUE THREAD

**Issue by q326066766** [xlfsummer/mp-painter#24]
图像使用height: "auto"会报错
还有为什么已经设置好宽高了
![image](https://user-images.githubusercontent.com/9585379/87223740-e792b280-c3b1-11ea-87b9-fb1c019f3693.png)

但是显示出来一直都是限制在300*150?
![image](https://user-images.githubusercontent.com/9585379/87223745-f37e7480-c3b1-11ea-926f-015031d4845e.png)

**Comment by xlfsummer** [comment]
- image 元素目前不支持 `height:  "auto"`
- 300 × 150 应该是 canvas 元素的默认尺寸

**Comment by q326066766** [comment]
> * 图像元素目前不支持`height:  "auto"`
> * 300×150应该是帆布元素的默认尺寸
设置canvas也没效果吖?
`<canvas style="width: 100%; height:100%" canvas-id="canvas"></canvas>`

**Comment by xlfsummer** [comment]
可以先用 1500 的 canvas 绘制并导出，生成一个 1500 的图片，拿到图片临时地址之后，再用一个 750 的 image 元素来显示

**Comment by q326066766** [comment]
喔明白了,现在有个问题,在微信小程序下能正常渲染背景色,但H5下第一次渲染时背景色变成透明的,重新渲染一次就正常了,不知道是不是BUG,还在排查,用的是HX开发工具的内部浏览器

**Comment by xlfsummer** [comment]
mp-painter 没有自动绘制背景，请手动绘制一次背景（使用 rect）

**Comment by xlfsummer** [comment]
> 还有有时渲染出来的图片变形

这个可以详细说一下复现步骤

**Comment by q326066766** [comment]
要不加你QQ然后展示给你看下,github上不好展示,然后如果先用 1500 的 canvas 绘制并导出，生成一个 1500 的图片，拿到图片临时地址之后，再用一个 750 的 image 元素来显示,那我要如何才能确定canvas已经绘制完成?

**Comment by q326066766** [comment]
这个可以详细说一下复现步骤 ,
![image](https://user-images.githubusercontent.com/9585379/87865191-c549f780-c9a4-11ea-8ea8-412e2284520c.png)

**Comment by xlfsummer** [comment]
> 那我要如何才能确定canvas已经绘制完成?

Painter.prototype.draw 是一个异步方法，所以可以用 `await` 或 `.then` 来控制流程
```js
await Painter(xxxxxx).draw(xxxxxxx)
// 这里可以确定绘制已完成
```

**Comment by xlfsummer** [comment]
@q326066766  
图片变形问题请移步新 issue 讨论 https://github.com/xlfsummer/mp-painter/issues/31

**Comment by MirShi** [comment]
现在的宽高可以设置auto吗？我用的1.0.1版本设置后还会报错
