### ISSUE TITLE
绘制视频

### ISSUE THREAD

**Issue by z605666069** [xlfsummer/mp-painter#27]
需要获取视频第一帧，所以需要绘制视频，有没有可以放video的画布

**Comment by xlfsummer** [comment]
可以尝试使用 [wx.chooseMedia](https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html) 获取视频缩略图的图片路径，再用该路径来绘制。不支持 canvas 直接绘制视频。

**Comment by z605666069** [comment]
> 可以尝试使用 [wx.chooseMedia](https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html) 获取视频缩略图的图片路径，再用该路径来绘制。不支持 canvas 直接绘制视频。

请问H5有办法吗

**Comment by xlfsummer** [comment]
真正的 ctx 支持绘制 video，你可以尝试获取真实的 ctx 对象来绘制（也就是说不通过 [uni.createCanvasContext](https://uniapp.dcloud.io/api/canvas/createCanvasContext), 而是拿到 canvas 对象后调用 `getContext` 方法来获取 ctx） 

mp-painter 中暂时不考虑做任何改动来支持这个特性
