### ISSUE TITLE
drawImage,不能得到绘制结束准确时间点

### ISSUE THREAD

**Issue by icepual** [xlfsummer/mp-painter#28]
在element-image第78行,drawImage没有添加await.我需要在图片绘制完成之后生成图片,现在经常造成生成图片出现空白.希望这里进行一下改进

**Comment by xlfsummer** [comment]
根据 [文档](https://uniapp.dcloud.io/api/canvas/CanvasContext?id=canvascontextdrawimage)，`drawImage` 并不是一个异步方法，所以在它前面写 `await` 是没用的
