### ISSUE TITLE
demo 网站挂了

### ISSUE THREAD

**Issue by lbc19920615** [xlfsummer/mp-painter#34]
#### 问题描述
demo 网站挂了 https://mp-painter.xlf-summer.cn/

#### 期望的结果
修复网站访问

**Comment by xlfsummer** [comment]
可以访问：
![image](https://user-images.githubusercontent.com/20750969/89495169-4816e300-d7ea-11ea-9e64-5c2d38b5f34a.png)

遇到无法访问的情况可尝试使用科学上网方法
