### ISSUE TITLE
不确定高度的内容，能加背景色吗？

### ISSUE THREAD

**Issue by suwei0708** [xlfsummer/mp-painter#40]
1、海报内段落文本有背景色，不确定高度，这个能实现吗？
2、海报内某块区域有背景色，有文字有图片，文字不确定高度，这个能实现吗？
上面使用rect，但是rect要写死高度，不能达到目的

**Comment by xlfsummer** [comment]
目前没有公开的接口专门来获取任意元素的高度，仅有 `Painter.protoype.draw` 方法可以获取所绘制元素的尺寸。

所以如果要实现你所说的需求，目前只能多次调用 draw。

后面会增加专门接口来获取任意元素的尺寸。

**Comment by suwei0708** [comment]
好的，谢谢，先这样使用，期待更新

**Comment by xlfsummer** [comment]
已在 beta 版中增加了此功能，可查看 [示例](https://mp-painter.xlf-summer.cn/#/pages/dynamicCanvasSize/dynamicCanvasSize)

也可以使用 `npm install --save mp-painter@next` 下载安装体验
