### ISSUE TITLE
uni端 希望可以增加一个 获取图片临时链接的方法，，目前只能看到不能获取到

### ISSUE THREAD

**Issue by buhtib** [xlfsummer/mp-painter#46]
uni端 希望可以增加一个 获取图片临时链接的方法，，目前只能看到不能获取到

**Comment by xlfsummer** [comment]
可以使用 [uni.downloadFile](https://uniapp.dcloud.io/api/request/network-file?id=downloadfile), mp-painter 中也是使用此方法

**Comment by buhtib** [comment]
> 可以使用 [uni.downloadFile](https://uniapp.dcloud.io/api/request/network-file?id=downloadfile), mp-painter 中也是使用此方法

uni.canvasToTempFilePath  应该是这个吧 ，，那个是转换网络链接
