### ISSUE TITLE
uni端 layout属性不支持

### ISSUE THREAD

**Issue by buhtib** [xlfsummer/mp-painter#47]
^0.2.13 版本  

uni端 layout属性不支持

**Comment by xlfsummer** [comment]
你好，layout 是在 1.0.0.beta-1 引入的，请使用 npm i mp-painter@next 安装 beta 版

**Comment by buhtib** [comment]
> 你好，layout是在1.0.0.beta-1的，请使用npm i mp-painter @ next安装beta版

![image](https://user-images.githubusercontent.com/42376795/104976469-3774c500-5a38-11eb-98b9-6392448b4ddc.png)
uni安装beta版本在小程序报错

**Comment by xlfsummer** [comment]
> > 你好，layout是在1.0.0.beta-1的，请使用npm i mp-painter @ next安装beta版
> 
> ![image](https://user-images.githubusercontent.com/42376795/104976469-3774c500-5a38-11eb-98b9-6392448b4ddc.png)
> uni安装beta版本在小程序报错

请开新 issue 反馈此问题
