### ISSUE TITLE
uniapp 中 Paitner 实例设置到 data 对象上报错

### ISSUE THREAD

**Issue by buhtib** [xlfsummer/mp-painter#48]
uni安装beta版本在小程序报错

![image](https://user-images.githubusercontent.com/42376795/104979730-f1bbfa80-5a3f-11eb-8619-7392ffccab0c.png)

**Comment by xlfsummer** [comment]
复现步骤和代码？

**Comment by buhtib** [comment]
> 复现步骤和代码？

![image](https://user-images.githubusercontent.com/42376795/104980782-62641680-5a42-11eb-9855-6dcb8c077280.png)
![image](https://user-images.githubusercontent.com/42376795/104980798-6abc5180-5a42-11eb-9925-eb2daa5d0305.png)
![image](https://user-images.githubusercontent.com/42376795/104980806-70b23280-5a42-11eb-9992-ac99443c45cf.png)

**Comment by buhtib** [comment]
> 复现步骤和代码？

![image](https://user-images.githubusercontent.com/42376795/104980911-9b9c8680-5a42-11eb-8e89-c3420a0d7d60.png)
![image](https://user-images.githubusercontent.com/42376795/104980954-af47ed00-5a42-11eb-8644-e0ab6dc60999.png)

**Comment by buhtib** [comment]
> 复现步骤和代码

**Comment by buhtib** [comment]
> 复现步骤和代码？

一进入页面 onReady中设置canvas直接报错

![Uploading image.png…]()

**Comment by buhtib** [comment]
> 复现步骤和代码？

一进入页面 onReady中设置canvas直接报错
![image](https://user-images.githubusercontent.com/42376795/104981216-2bdacb80-5a43-11eb-96d7-acd2fff7451c.png)

**Comment by xlfsummer** [comment]
Painter 的实例目前包含循环引用，请勿将 Painter 的实例保存到 data 中

**Comment by buhtib** [comment]
> Painter 的实例目前包含循环引用，请勿将 Painter 的实例保存到 data 中

大概什么时候可以修复🤓

**Comment by xlfsummer** [comment]
应该最近就可以修复，可以先使用下面的 work around 试试:
```js
const painter = new Painter(uni.createCanvasContext("canvas"));

// 支持序列化放到 data 上
painter.toJSON = () => "";

this.canvasPainter = painter;
```
